// Code generation: s-expressions to AArch64 assembly text.
//
// Ghuloum-style: every expression leaves its value in x0, and values that
// have to wait (a binary op's left operand, a let's value) go to slots in
// the function's frame. No register allocation.
//
// The output is a .S file that includes runtime/asm.h, so the differences
// between Mach-O and ELF stay in one header, and rt.h's constants (RT_TRUE,
// RT_FAULT_OVERFLOW, ...) can be used by name.
//
// Step 1 (docs/PLAN.md): integers, #true/#false, (), the integer
// primitives, cond, let, do, and pprint. A program's top-level forms are
// the body of slight_main.

import { CompileError } from './errors.ts';
import { posOf, show, toArray, type Pair, type Pos, type Sexp, type Sym } from './sexp.ts';
import { intWord, RESERVED_SYMBOLS } from './values.ts';

// Lines of assembly, as a tree, so that joining pieces is cheap. flatten()
// turns it into lines once at the end.
type Code = string | readonly Code[];

// The locals in scope, innermost first: an association list from name to
// frame slot.
type Env = { readonly name: string; readonly slot: number; readonly next: Env } | null;

// What compiling accumulates: how many labels have been made, how many
// frame slots the function needs, and the out-of-line code (fault calls)
// and read-only data to emit after it.
type St = { readonly labels: number; readonly slots: number; readonly stubs: Code; readonly data: Code };

const SPECIAL_FORMS: readonly string[] = ['defun', 'lambda', 'let', 'cond', 'do', 'quote', 'fork', 'connect', 'recv', 'yield'];

// --- the program ------------------------------------------------------------

export function compileProgram(forms: Sexp): string {
    if (forms.t === 'nil') throw new CompileError('the program is empty', null);
    const [body, st] = compileBody(forms, null, 0, { labels: 0, slots: 0, stubs: [], data: [] });
    const code: Code = [
        '// generated by slightc -- do not edit',
        '#include "asm.h"',
        '',
        compileFunction('slight_main', body, st.slots),
        st.stubs,
        '',
        '    RODATA',
        st.data,
        symbolTable(RESERVED_SYMBOLS),
    ];
    return flatten(code).join('\n') + '\n';
}

// The frame: x29/x30 on top, then the slots, addressed up from sp.
function compileFunction(name: string, body: Code, slots: number): Code {
    const size = 16 * Math.ceil(slots / 2);
    if (size > 4095) throw new CompileError(`${name} needs too many frame slots (${slots})`, null);
    return [
        `FUNC ${name}`,
        '    stp  x29, x30, [sp, #-16]!',
        '    mov  x29, sp',
        size > 0 ? `    sub  sp, sp, #${size}` : [],
        body,
        '    mov  sp, x29',
        '    ldp  x29, x30, [sp], #16',
        '    ret',
    ];
}

// Every symbol's name, in id order, for the runtime's printer.
function symbolTable(names: readonly string[]): Code {
    return [
        '    .p2align 3',
        '    .globl slight_symbol_count',
        'slight_symbol_count:',
        `    .quad ${names.length}`,
        '    .globl slight_symbol_names',
        'slight_symbol_names:',
        names.map((name) => `    .asciz ${asmString(name)}`),
    ];
}

// --- bodies and expressions -------------------------------------------------

// A body: forms evaluated in order, leaving the last one's value in x0.
// (let name expr) binds name for the rest of the body; as the last form,
// its value is expr's, as in ts-slight.
function compileBody(forms: Sexp, env: Env, si: number, st: St): [Code, St] {
    if (forms.t !== 'pair') return [[], st];
    const form = forms.car;
    if (form.t === 'pair' && form.car.t === 'sym' && form.car.name === 'let') {
        const [name, expr] = checkLet(form);
        const [code, st1] = compileExpr(expr, env, si, st);
        if (forms.cdr.t === 'nil') return [code, st1];
        const inner: Env = { name: name.name, slot: si, next: env };
        const [rest, st2] = compileBody(forms.cdr, inner, si + 1, useSlot(st1, si));
        return [[code, `    str  x0, ${slot(si)}    // ${name.name}`, rest], st2];
    }
    const [code, st1] = compileExpr(form, env, si, st);
    const [rest, st2] = compileBody(forms.cdr, env, si, st1);
    return [[code, rest], st2];
}

function checkLet(form: Pair): [Sym, Sexp] {
    const items = toArray(form) ?? [];
    const [, name, expr] = items;
    if (items.length !== 3 || name === undefined || expr === undefined) {
        throw new CompileError(`let is (let name expr), not ${show(form)}`, form.pos);
    }
    if (name.t !== 'sym') throw new CompileError(`let needs a name, not ${show(name)}`, posOf(name) ?? form.pos);
    if (RESERVED_SYMBOLS.includes(name.name) || SPECIAL_FORMS.includes(name.name)) {
        throw new CompileError(`can't bind ${name.name}`, name.pos);
    }
    return [name, expr];
}

// si is the first free frame slot: anything below it belongs to someone.
function compileExpr(x: Sexp, env: Env, si: number, st: St): [Code, St] {
    switch (x.t) {
        case 'int': {
            const [first, ...rest] = loadWord('x0', intWord(x.v));
            return [[`${first}    // ${x.v}`, rest], st];
        }
        case 'nil':
            return ['    mov  x0, #RT_NIL', st];
        case 'sym':
            return [compileName(x, env), st];
        case 'pair':
            return compileForm(x, env, si, st);
        default:
            throw notYet(x);
    }
}

function compileName(x: Sym, env: Env): Code {
    if (x.name === '#true') return '    mov  x0, #RT_TRUE';
    if (x.name === '#false') return '    mov  x0, #RT_FALSE';
    const si = lookup(env, x.name);
    if (si === null) throw new CompileError(`unknown name '${x.name}'`, x.pos);
    return `    ldr  x0, ${slot(si)}    // ${x.name}`;
}

function compileForm(x: Pair, env: Env, si: number, st: St): [Code, St] {
    const head = x.car;
    const args = toArray(x.cdr)!;
    if (head.t !== 'sym') throw notYet(x);
    switch (head.name) {
        case 'cond':
            return compileCond(x, args, env, si, st);
        case 'do':
            if (args.length === 0) throw new CompileError('do needs at least one form', x.pos);
            return compileBody(x.cdr, env, si, st);
        case 'let':
            throw new CompileError('let can only be a form of a body (a function, do or cond clause)', x.pos);
    }
    if (SPECIAL_FORMS.includes(head.name)) throw notYet(x);
    if (lookup(env, head.name) !== null) throw notYet(x);      // calling a local: closures, step 6
    if (head.name === 'pprint') {
        checkArity(x, 'pprint', args, 1);
        const [code, st1] = compileExpr(args[0]!, env, si, st);
        return [[code, '    bl   rt_pprint'], st1];
    }
    const arith = ARITH[head.name];
    if (arith !== undefined) {
        return compileBinary(x, head.name, args, env, si, st, (s) => {
            const [overflow, s1] = faultLabel(s, 'RT_FAULT_OVERFLOW', head.name, x.pos);
            return [arith(overflow), s1];
        });
    }
    const cond = COMPARE[head.name];
    if (cond !== undefined) return compileBinary(x, head.name, args, env, si, st, (s) => [compare(cond), s]);
    throw new CompileError(`unknown function '${head.name}'`, head.pos);
}

// --- primitives ---------------------------------------------------------------

// Integer arithmetic on x1 (left) and x0 (right), both known to be
// integers, into x0, branching to `overflow` when the result doesn't fit.
const ARITH: Readonly<Record<string, (overflow: string) => Code>> = {
    // Tagged integers are n << 1, so adding or subtracting the words adds or
    // subtracts the integers, and 64-bit overflow is exactly 63-bit overflow.
    '+': (overflow) => ['    adds x0, x1, x0', `    b.vs ${overflow}`],
    '-': (overflow) => ['    subs x0, x1, x0', `    b.vs ${overflow}`],
    // (a << 1) * b = (a * b) << 1: untag one side. It overflows when the high
    // half of the 128-bit product isn't just the low half's sign.
    '*': (overflow) => [
        '    asr  x2, x0, #1',
        '    smulh x3, x1, x2',
        '    mul  x0, x1, x2',
        '    cmp  x3, x0, asr #63',
        `    b.ne ${overflow}`,
    ],
};

// Integer comparisons, by condition code. Tagging keeps the order, so the
// words compare like the integers.
const COMPARE: Readonly<Record<string, string>> = { '==': 'eq', '!=': 'ne', '<': 'lt', '<=': 'le', '>': 'gt', '>=': 'ge' };

const compare = (cond: string): Code => [
    '    cmp  x1, x0',
    '    mov  x0, #RT_TRUE',
    '    mov  x2, #RT_FALSE',
    `    csel x0, x0, x2, ${cond}`,
];

// Both operands must be integers. The left one waits in slot si while the
// right one is computed; then op combines x1 (left) and x0 (right).
function compileBinary(x: Pair, name: string, args: readonly Sexp[], env: Env, si: number, st: St,
                       op: (st: St) => [Code, St]): [Code, St] {
    checkArity(x, name, args, 2);
    const [left, st1]   = compileExpr(args[0]!, env, si, st);
    const [right, st2]  = compileExpr(args[1]!, env, si + 1, useSlot(st1, si));
    const [notInt, st3] = faultLabel(st2, 'RT_FAULT_NOT_INT', name, x.pos);
    const [combine, st4] = op(st3);
    const isInt = ['    tst  x0, #1', `    b.ne ${notInt}`];
    return [[
        left, isInt, `    str  x0, ${slot(si)}`,
        right, isInt, `    ldr  x1, ${slot(si)}`,
        combine,
    ], st4];
}

function checkArity(x: Pair, name: string, args: readonly Sexp[], n: number): void {
    if (args.length !== n) {
        throw new CompileError(`${name} takes ${n} argument${n === 1 ? '' : 's'}, not ${args.length}`, x.pos);
    }
}

// --- cond -------------------------------------------------------------------

// Each test must be #true or #false; anything else faults, and so does
// running out of clauses. A test that is literally #true needs no check.
function compileCond(x: Pair, clauses: readonly Sexp[], env: Env, si: number, st: St): [Code, St] {
    if (clauses.length === 0) throw new CompileError('cond needs at least one clause', x.pos);
    const [end, st1]     = label(st, 'cond_end');
    const [noMatch, st2] = faultLabel(st1, 'RT_FAULT_NO_CLAUSE', 'cond', x.pos);
    const [code, st3]    = clauses.reduce<[Code, St]>(([acc, s], clause) => {
        const [c, s1] = compileClause(x, clause, end, env, si, s);
        return [[acc, c], s1];
    }, [[], st2]);
    return [[code, `    b    ${noMatch}`, `${end}:`], st3];
}

function compileClause(x: Pair, clause: Sexp, end: string, env: Env, si: number, st: St): [Code, St] {
    if (clause.t !== 'pair' || clause.cdr.t !== 'pair') {
        throw new CompileError(`a cond clause is (test body...), not ${show(clause)}`, posOf(clause) ?? x.pos);
    }
    const test = clause.car;
    if (test.t === 'sym' && test.name === '#true') {
        const [body, st1] = compileBody(clause.cdr, env, si, st);
        return [[body, `    b    ${end}`], st1];
    }
    const [code, st1]    = compileExpr(test, env, si, st);
    const [body, st2]    = compileBody(clause.cdr, env, si, st1);
    const [next, st3]    = label(st2, 'cond_next');
    const [notBool, st4] = faultLabel(st3, 'RT_FAULT_NOT_BOOL', 'cond test', posOf(test) ?? clause.pos);
    return [[
        code,
        '    cmp  x0, #RT_FALSE',
        `    b.eq ${next}`,
        '    cmp  x0, #RT_TRUE',
        `    b.ne ${notBool}`,
        body,
        `    b    ${end}`,
        `${next}:`,
    ], st4];
}

// --- helpers ------------------------------------------------------------------

const slot = (si: number): string => `[sp, #${8 * si}]`;

const useSlot = (st: St, si: number): St => (si < st.slots ? st : { ...st, slots: si + 1 });

function lookup(env: Env, name: string): number | null {
    for (; env !== null; env = env.next) if (env.name === name) return env.slot;
    return null;
}

function label(st: St, hint: string): [string, St] {
    return [`L${hint}_${st.labels}`, { ...st, labels: st.labels + 1 }];
}

type Fault = 'RT_FAULT_NOT_INT' | 'RT_FAULT_OVERFLOW' | 'RT_FAULT_NOT_BOOL' | 'RT_FAULT_NO_CLAUSE';

// A label to branch to when `what`, at `pos`, goes wrong: an out-of-line
// call to rt_fault, with the offending value (if any) in x0.
function faultLabel(st: St, fault: Fault, what: string, pos: Pos | null): [string, St] {
    const [name, st1] = label(st, 'fault');
    const site = pos === null ? what : `${what} at ${pos.file}:${pos.line}:${pos.col}`;
    const stub = [
        `${name}:`,
        '    mov  x1, x0',
        `    mov  x0, #${fault}`,
        `    LOADADDR x2, ${name}_site`,
        '    bl   rt_fault',
    ];
    const data = [`${name}_site:`, `    .asciz ${asmString(site)}`];
    return [name, { ...st1, stubs: [st1.stubs, stub], data: [st1.data, data] }];
}

const notYet = (x: Sexp): CompileError => new CompileError(`not supported yet: ${show(x)}`, posOf(x));

// A string as an assembler literal: printable ASCII as is, everything else
// (and " and \) as octal escapes of its UTF-8 bytes.
export function asmString(s: string): string {
    const bytes = [...new TextEncoder().encode(s)];
    const esc   = (b: number): string =>
        b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c ? String.fromCharCode(b) : `\\${b.toString(8).padStart(3, '0')}`;
    return `"${bytes.map(esc).join('')}"`;
}

function flatten(code: Code): string[] {
    const out: string[] = [];
    const todo: Code[] = [code];
    while (todo.length > 0) {
        const c = todo.pop()!;
        if (typeof c === 'string') out.push(c);
        else for (let i = c.length - 1; i >= 0; i--) todo.push(c[i]!);
    }
    return out;
}

// The shortest movz/movn + movk sequence that puts a 64-bit word in reg:
// start from all zeros (movz) or all ones (movn), whichever leaves fewer
// 16-bit chunks to patch with movk.
export function loadWord(reg: string, word: bigint): readonly string[] {
    const w      = BigInt.asUintN(64, word);
    const chunks = [0, 1, 2, 3].map((k) => ({ k, v: Number((w >> BigInt(16 * k)) & 0xffffn) }));
    const ones   = chunks.filter((c) => c.v === 0xffff).length;
    const zeros  = chunks.filter((c) => c.v === 0).length;
    const fill   = ones > zeros ? 0xffff : 0;
    const [first, ...rest] = chunks.filter((c) => c.v !== fill);
    const hex    = (n: number): string => `#0x${n.toString(16)}`;
    const head   = first === undefined
        ? `    ${fill === 0 ? 'movz' : 'movn'} ${reg}, #0`
        : fill === 0
            ? `    movz ${reg}, ${hex(first.v)}, lsl #${16 * first.k}`
            : `    movn ${reg}, ${hex(~first.v & 0xffff)}, lsl #${16 * first.k}`;
    return [head, ...rest.map((c) => `    movk ${reg}, ${hex(c.v)}, lsl #${16 * c.k}`)];
}
