// Code generation: s-expressions to AArch64 assembly text.
//
// Ghuloum-style: every expression leaves its value in x0, and values that
// have to wait (arguments, a binary op's left operand, a let's value) go to
// slots in the function's frame. No register allocation, and nothing lives
// in a register across a call.
//
// Functions take their arguments in x0..x7 and return their result in x0,
// as in AAPCS64, so compiled functions and the runtime's C functions are
// called the same way. A call in tail position takes down the caller's
// frame and jumps, so loops run in constant stack.
//
// The output is a .S file that includes runtime/asm.h, so the differences
// between Mach-O and ELF stay in one header, and rt.h's constants (RT_TRUE,
// RT_FAULT_OVERFLOW, ...) can be used by name.
//
// So far (docs/PLAN.md, steps 1-4): integers, #true/#false, (), symbols,
// lists (cons cells bump-allocated in the process's heap, or static data
// when quoted), the integer and list primitives, eq?/ne?, type predicates,
// cond, let, do, pprint, defun and calls. The top-level forms that aren't
// defuns are the body of slight_main.

import { CompileError } from './errors.ts';
import { list, NIL, posOf, show, toArray, type Pair, type Pos, type Sexp, type Sym } from './sexp.ts';
import { intWord, RESERVED_SYMBOLS, symbolWord } from './values.ts';

// Lines of assembly, as a tree, so that joining pieces is cheap. flatten()
// turns it into lines once at the end.
type Code = string | readonly Code[];

// The locals in scope, innermost first: an association list from name to
// frame slot.
type Env = { readonly name: string; readonly slot: number; readonly next: Env } | null;

// The top-level functions: an association list from name to label and arity.
type Fn  = { readonly name: string; readonly label: string; readonly arity: number };
type Fns = { readonly fn: Fn; readonly next: Fns } | null;

// Where an expression is being compiled: the functions and locals it can
// see, the first free frame slot (anything below si belongs to someone),
// and whether it's in tail position.
type Cx = { readonly fns: Fns; readonly env: Env; readonly si: number; readonly tail: boolean };

// The symbols seen so far, newest first: an association list from name to
// id. Ids are handed out in order, starting with the reserved symbols.
type Syms = { readonly name: string; readonly id: number; readonly next: Syms } | null;

// What compiling accumulates: how many labels have been made, how many
// frame slots the current function needs, the symbols, the out-of-line
// code (fault calls, preemption) to emit after all the functions, and the
// read-only data: strings (data) and quoted lists (consts).
type St = {
    readonly labels: number;
    readonly slots: number;
    readonly symbols: Syms;
    readonly stubs: Code;
    readonly data: Code;
    readonly consts: Code;
};

const MAX_ARGS = 8;     // x0..x7

const SPECIAL_FORMS: readonly string[] = ['defun', 'lambda', 'let', 'cond', 'do', 'quote', 'fork', 'connect', 'recv', 'yield'];

// Takes down the frame that the prologue in compileFunction built.
const EPILOGUE: Code = ['    mov  sp, x29', '    ldp  x29, x30, [sp], #16'];

// --- the program ------------------------------------------------------------

export function compileProgram(forms: Sexp): string {
    const all     = toArray(forms)!;
    const defuns  = all.filter((f) => isForm(f, 'defun')).map((f) => checkDefun(f as Pair));
    const fns     = defuns.reduce<Fns>(declare, null);
    const top     = all.filter((f) => !isForm(f, 'defun'));
    const empty: St = { labels: 0, slots: 0, symbols: null, stubs: [], data: [], consts: [] };
    const st0 = RESERVED_SYMBOLS.reduce((st, name) => symbolId(st, name)[1], empty);

    const [code, st1] = defuns.reduce<[Code, St]>(([acc, st], d) => {
        const [c, s] = compileFunction(lookupFn(fns, d.name.name)!.label, d, fns, st);
        return [[acc, c], s];
    }, [[], st0]);
    const main: Defun = { name: { t: 'sym', name: 'the top level', pos: null }, params: [], body: list(...top, ...(top.length === 0 ? [NIL] : [])), pos: null };
    const [mainCode, st2] = compileFunction('slight_main', main, fns, st1);

    return flatten([
        '// generated by slightc -- do not edit',
        '#include "asm.h"',
        '',
        '    .text',
        code,
        mainCode,
        st2.stubs,
        '',
        '    RODATA',
        st2.data,
        symbolTable(st2.symbols),
        '',
        '    CONSTDATA',
        st2.consts,
    ]).join('\n') + '\n';
}

// Every symbol's name, in id order, for the runtime's printer.
function symbolTable(symbols: Syms): Code {
    const names: string[] = [];
    for (; symbols !== null; symbols = symbols.next) names.unshift(symbols.name);
    return [
        '    .p2align 3',
        '    .globl slight_symbol_count',
        'slight_symbol_count:',
        `    .quad ${names.length}`,
        '    .globl slight_symbol_names',
        'slight_symbol_names:',
        names.map((name) => `    .asciz ${asmString(name)}`),
    ];
}

// --- functions --------------------------------------------------------------

type Defun = { readonly name: Sym; readonly params: readonly Sym[]; readonly body: Sexp; readonly pos: Pos | null };

function checkDefun(x: Pair): Defun {
    const items = toArray(x)!;
    const [, name, params] = items;
    if (items.length < 4 || name === undefined || params === undefined) {
        throw new CompileError('defun is (defun name (params...) body...)', x.pos);
    }
    if (name.t !== 'sym') throw new CompileError(`defun needs a name, not ${show(name)}`, posOf(name) ?? x.pos);
    checkBindable(name);
    if (isBuiltin(name.name)) throw new CompileError(`can't define ${name.name}: it's a builtin`, name.pos);
    const ps = toArray(params);
    if (ps === null) throw new CompileError(`${name.name}'s parameters must be a list, not ${show(params)}`, posOf(params) ?? x.pos);
    const syms = ps.map((p) => {
        if (p.t !== 'sym') throw new CompileError(`a parameter must be a name, not ${show(p)}`, posOf(p) ?? x.pos);
        checkBindable(p);
        return p;
    });
    syms.forEach((p, i) => {
        if (syms.findIndex((q) => q.name === p.name) !== i) throw new CompileError(`${p.name} is a parameter twice`, p.pos);
    });
    if (syms.length > MAX_ARGS) {
        throw new CompileError(`${name.name} has ${syms.length} parameters; the most is ${MAX_ARGS}`, name.pos);
    }
    return { name, params: syms, body: list(...items.slice(3)), pos: x.pos };
}

function declare(fns: Fns, d: Defun): Fns {
    if (lookupFn(fns, d.name.name) !== null) throw new CompileError(`${d.name.name} is already defined`, d.name.pos);
    return { fn: { name: d.name.name, label: functionLabel(d.name.name), arity: d.params.length }, next: fns };
}

// The frame: x29/x30 on top, then the slots, addressed up from sp. The
// parameters go to the first slots straight away. Then two checks, which
// every call and every tail call passes through: is there room on the
// stack, and are this process's reductions used up?
function compileFunction(entry: string, d: Defun, fns: Fns, st: St): [Code, St] {
    const env = d.params.reduce<Env>((e, p, i) => ({ name: p.name, slot: i, next: e }), null);
    const cx: Cx = { fns, env, si: d.params.length, tail: true };
    const [body, st1] = compileBody(d.body, cx, { ...st, slots: d.params.length });
    const size = 16 * Math.ceil(st1.slots / 2);
    if (size > 4095) throw new CompileError(`${d.name.name} needs too many frame slots (${st1.slots})`, d.pos);
    const [overflow, st2] = faultLabel(st1, 'RT_FAULT_STACK', d.name.name, d.pos);
    const [preempt, st3]  = label(st2, 'preempt');
    const stub = [`${preempt}:`, '    mov  x0, x28', '    bl   rt_preempt', `    b    ${preempt}_done`];
    return [[
        '',
        entry === 'slight_main' ? 'FUNC slight_main' : ['    .p2align 2', `${entry}:    // ${d.name.name}`],
        '    stp  x29, x30, [sp, #-16]!',
        '    mov  x29, sp',
        size > 0 ? `    sub  sp, sp, #${size}` : [],
        '    ldr  x16, [x28, #RT_PROC_STACK_LIMIT]',
        '    cmp  sp, x16',
        `    b.lo ${overflow}`,
        d.params.map((p, i) => `    str  x${i}, ${slot(i)}    // ${p.name}`),
        '    ldr  x16, [x28, #RT_PROC_REDUCTIONS]',
        '    subs x16, x16, #1',
        '    str  x16, [x28, #RT_PROC_REDUCTIONS]',
        `    b.le ${preempt}`,
        `${preempt}_done:`,
        body,
        EPILOGUE,
        '    ret',
    ], { ...st3, stubs: [st3.stubs, stub] }];
}

// A call: each argument waits in a slot while the rest are computed, then
// they all go to x0..x7. In tail position the caller's frame comes down
// first, and the call is a jump.
function compileCall(x: Pair, fn: Fn, args: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    checkArity(x, fn.name, args, fn.arity);
    const [code, st1] = args.reduce<[Code, St]>(([acc, s], arg, i) => {
        const [c, s1] = compileExpr(arg, { ...cx, si: cx.si + i, tail: false }, s);
        return [[acc, c, `    str  x0, ${slot(cx.si + i)}`], useSlot(s1, cx.si + i)];
    }, [[], st]);
    const loads = args.map((_, i) => `    ldr  x${i}, ${slot(cx.si + i)}`);
    const call  = cx.tail ? [EPILOGUE, `    b    ${fn.label}    // tail call`] : `    bl   ${fn.label}`;
    return [[code, loads, call], st1];
}

// The assembler label for a function: fn_ and the name, with anything but
// letters and digits spelled out (_ as __, other bytes as _ and two hex
// digits), so that different names never get the same label.
export function functionLabel(name: string): string {
    const isAlnum = (b: number): boolean => (b >= 0x30 && b <= 0x39) || (b >= 0x41 && b <= 0x5a) || (b >= 0x61 && b <= 0x7a);
    const spell   = (b: number): string =>
        isAlnum(b) ? String.fromCharCode(b) : b === 0x5f ? '__' : `_${b.toString(16).padStart(2, '0')}`;
    return `fn_${[...new TextEncoder().encode(name)].map(spell).join('')}`;
}

// --- bodies and expressions -------------------------------------------------

// A body: forms evaluated in order, leaving the last one's value in x0.
// (let name expr) binds name for the rest of the body; as the last form,
// its value is expr's, as in ts-slight. Only the last form can be in tail
// position.
function compileBody(forms: Sexp, cx: Cx, st: St): [Code, St] {
    if (forms.t !== 'pair') return [[], st];
    const last = forms.cdr.t === 'nil';
    const here: Cx = { ...cx, tail: cx.tail && last };
    const form = forms.car;
    if (isForm(form, 'let')) {
        const [name, expr] = checkLet(form as Pair);
        const [code, st1] = compileExpr(expr, here, st);
        if (last) return [code, st1];
        const inner: Cx = { ...cx, env: { name: name.name, slot: cx.si, next: cx.env }, si: cx.si + 1 };
        const [rest, st2] = compileBody(forms.cdr, inner, useSlot(st1, cx.si));
        return [[code, `    str  x0, ${slot(cx.si)}    // ${name.name}`, rest], st2];
    }
    const [code, st1] = compileExpr(form, here, st);
    const [rest, st2] = compileBody(forms.cdr, cx, st1);
    return [[code, rest], st2];
}

function checkLet(form: Pair): [Sym, Sexp] {
    const items = toArray(form) ?? [];
    const [, name, expr] = items;
    if (items.length !== 3 || name === undefined || expr === undefined) {
        throw new CompileError(`let is (let name expr), not ${show(form)}`, form.pos);
    }
    if (name.t !== 'sym') throw new CompileError(`let needs a name, not ${show(name)}`, posOf(name) ?? form.pos);
    checkBindable(name);
    return [name, expr];
}

// Names that can't be bound or defined: #true, #false and the special forms.
function checkBindable(name: Sym): void {
    if (RESERVED_SYMBOLS.includes(name.name) || SPECIAL_FORMS.includes(name.name)) {
        throw new CompileError(`can't bind ${name.name}`, name.pos);
    }
}

function compileExpr(x: Sexp, cx: Cx, st: St): [Code, St] {
    switch (x.t) {
        case 'int': {
            const [first, ...rest] = loadWord('x0', intWord(x.v));
            return [[`${first}    // ${x.v}`, rest], st];
        }
        case 'nil':
            return ['    mov  x0, #RT_NIL', st];
        case 'sym':
            return [compileName(x, cx), st];
        case 'pair':
            return compileForm(x, cx, st);
        default:
            throw notYet(x);
    }
}

function compileName(x: Sym, cx: Cx): Code {
    if (x.name === '#true') return '    mov  x0, #RT_TRUE';
    if (x.name === '#false') return '    mov  x0, #RT_FALSE';
    const si = lookup(cx.env, x.name);
    if (si !== null) return `    ldr  x0, ${slot(si)}    // ${x.name}`;
    if (lookupFn(cx.fns, x.name) !== null) throw new CompileError(`functions as values aren't supported yet: ${x.name}`, x.pos);
    throw new CompileError(`unknown name '${x.name}'`, x.pos);
}

function compileForm(x: Pair, cx: Cx, st: St): [Code, St] {
    const head = x.car;
    const args = toArray(x.cdr)!;
    if (head.t !== 'sym') throw notYet(x);
    switch (head.name) {
        case 'cond':
            return compileCond(x, args, cx, st);
        case 'do':
            if (args.length === 0) throw new CompileError('do needs at least one form', x.pos);
            return compileBody(x.cdr, cx, st);
        case 'let':
            throw new CompileError('let can only be a form of a body (a function, do or cond clause)', x.pos);
        case 'defun':
            throw new CompileError('defun is only allowed at the top level', x.pos);
        case 'quote':
            return compileQuote(x, args, cx, st);
    }
    if (SPECIAL_FORMS.includes(head.name)) throw notYet(x);
    if (lookup(cx.env, head.name) !== null) throw notYet(x);   // calling a local: closures, step 6
    const operand: Cx = { ...cx, tail: false };
    if (head.name === 'pprint') {
        checkArity(x, 'pprint', args, 1);
        const [code, st1] = compileExpr(args[0]!, operand, st);
        return [[code, '    bl   rt_pprint'], st1];
    }
    const predicate = PREDICATES[head.name];
    if (predicate !== undefined) {
        checkArity(x, head.name, args, 1);
        const [code, st1] = compileExpr(args[0]!, operand, st);
        return [[code, predicate[0], boolIf(predicate[1])], st1];
    }
    if (head.name === 'eq?' || head.name === 'ne?') return compileEquality(x, head.name, args, operand, st);
    if (head.name === 'cons') return compileCons(x, args, operand, st);
    if (head.name === 'list') return compileList(x, args, operand, st);
    const path = cxrPath(head.name);
    if (path !== null) return compileCxr(x, head.name, path, args, operand, st);
    const arith = ARITH[head.name];
    if (arith !== undefined) {
        return compileBinary(x, head.name, args, operand, st, (s) => {
            const [overflow, s1] = faultLabel(s, 'RT_FAULT_OVERFLOW', head.name, x.pos);
            return [arith(overflow), s1];
        });
    }
    const cond = COMPARE[head.name];
    if (cond !== undefined) return compileBinary(x, head.name, args, operand, st, (s) => [compare(cond), s]);
    const fn = lookupFn(cx.fns, head.name);
    if (fn !== null) return compileCall(x, fn, args, cx, st);
    throw new CompileError(`unknown function '${head.name}'`, head.pos);
}

const isForm = (x: Sexp, name: string): boolean => x.t === 'pair' && x.car.t === 'sym' && x.car.name === name;

// A constant. Symbols are their compile-time ids; integers and () quote
// to themselves; a quoted list is static data, shared by every process and
// never copied or collected. Strings and floats need boxes (step 5).
function compileQuote(x: Pair, args: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    checkArity(x, 'quote', args, 1);
    const datum = args[0]!;
    if (datum.t === 'int' || datum.t === 'nil') return compileExpr(datum, cx, st);
    if (datum.t === 'pair') {
        const [name, st1] = staticList(x, datum, st);
        return [[`    LOADADDR x0, ${name}`, '    orr  x0, x0, #RT_TAG_LIST'], st1];
    }
    if (datum.t !== 'sym') throw notYet(x);
    const [id, st1] = symbolId(st, datum.name);
    const [first, ...rest] = loadWord('x0', symbolWord(id));
    return [[`${first}    // '${datum.name}`, rest], st1];
}

// A quoted list's cells, side by side in the constant data, each one's
// cdr pointing at the next; nested lists first, so their words are known.
// Returns the label of the first cell.
function staticList(x: Pair, list: Pair, st: St): [string, St] {
    const [words, st1] = toArray(list)!.reduce<[readonly string[], St]>(([ws, s], item) => {
        const [w, s1] = staticWord(x, item, s);
        return [[...ws, w], s1];
    }, [[], st]);
    const [name, st2] = label(st1, 'quoted');
    const cells = words.map((w, i) => `    .quad ${w}, ${i + 1 < words.length ? `${name}+${16 * (i + 1) + RT_TAG_LIST}` : 'RT_NIL'}`);
    return [name, { ...st2, consts: [st2.consts, '    .p2align 4', `${name}:`, cells] }];
}

function staticWord(x: Pair, item: Sexp, st: St): [string, St] {
    switch (item.t) {
        case 'int':
            return [`0x${BigInt.asUintN(64, intWord(item.v)).toString(16)}`, st];
        case 'nil':
            return ['RT_NIL', st];
        case 'sym': {
            const [id, st1] = symbolId(st, item.name);
            return [`0x${symbolWord(id).toString(16)}`, st1];
        }
        case 'pair': {
            const [name, st1] = staticList(x, item, st);
            return [`${name}+${RT_TAG_LIST}`, st1];
        }
        default:
            throw notYet(x);
    }
}

function symbolId(st: St, name: string): [number, St] {
    for (let s = st.symbols; s !== null; s = s.next) if (s.name === name) return [s.id, st];
    const id = st.symbols === null ? 0 : st.symbols.id + 1;
    return [id, { ...st, symbols: { name, id, next: st.symbols } }];
}

// --- primitives ---------------------------------------------------------------

// Integer arithmetic on x1 (left) and x0 (right), both known to be
// integers, into x0, branching to `overflow` when the result doesn't fit.
const ARITH: Readonly<Record<string, (overflow: string) => Code>> = {
    // Tagged integers are n << 1, so adding or subtracting the words adds or
    // subtracts the integers, and 64-bit overflow is exactly 63-bit overflow.
    '+': (overflow) => ['    adds x0, x1, x0', `    b.vs ${overflow}`],
    '-': (overflow) => ['    subs x0, x1, x0', `    b.vs ${overflow}`],
    // (a << 1) * b = (a * b) << 1: untag one side. It overflows when the high
    // half of the 128-bit product isn't just the low half's sign.
    '*': (overflow) => [
        '    asr  x2, x0, #1',
        '    smulh x3, x1, x2',
        '    mul  x0, x1, x2',
        '    cmp  x3, x0, asr #63',
        `    b.ne ${overflow}`,
    ],
};

// Integer comparisons, by condition code. Tagging keeps the order, so the
// words compare like the integers.
const COMPARE: Readonly<Record<string, string>> = { '==': 'eq', '!=': 'ne', '<': 'lt', '<=': 'le', '>': 'gt', '>=': 'ge' };

const RT_TAG_LIST = 1;

// Sets Z when x0 is not a cons: when its tag isn't the list tag, ccmp
// skips the second compare and sets Z (#4) itself; otherwise Z means nil.
const IS_CONS: Code = [
    '    and  x1, x0, #RT_TAG_MASK',
    '    cmp  x1, #RT_TAG_LIST',
    '    ccmp x0, #RT_NIL, #4, eq',
];

// Type predicates: a test of x0 that sets the flags, and the condition that
// means yes. #true and #false are symbols too, so sym? says yes to them.
const PREDICATES: Readonly<Record<string, readonly [Code, string]>> = {
    'int?':  [['    tst  x0, #1'], 'eq'],
    'nil?':  [['    cmp  x0, #RT_NIL'], 'eq'],
    'cons?': [IS_CONS, 'ne'],
    'sym?':  [['    and  x1, x0, #RT_TAG_MASK', '    cmp  x1, #RT_TAG_SYMBOL'], 'eq'],
    // when x0 is #true, ccmp skips the second compare and sets Z (#4) itself
    'bool?': [['    cmp  x0, #RT_TRUE', '    ccmp x0, #RT_FALSE, #4, ne'], 'eq'],
};

// The names a defun can't take.
const BUILTINS: readonly string[] =
    ['pprint', 'eq?', 'ne?', 'cons', 'list', ...[ARITH, COMPARE, PREDICATES].flatMap((table) => Object.keys(table))];

const isBuiltin = (name: string): boolean => BUILTINS.includes(name) || cxrPath(name) !== null;

// x0 = #true if cond holds, otherwise #false.
const boolIf = (cond: string): Code => ['    mov  x0, #RT_TRUE', '    mov  x2, #RT_FALSE', `    csel x0, x0, x2, ${cond}`];

const compare = (cond: string): Code => ['    cmp  x1, x0', boolIf(cond)];

// The left operand waits in slot si while the right one is computed; then
// op combines x1 (left) and x0 (right). With ints, both must be integers.
function compileBinary(x: Pair, name: string, args: readonly Sexp[], cx: Cx, st: St,
                       op: (st: St) => [Code, St], ints = true): [Code, St] {
    checkArity(x, name, args, 2);
    const [left, st1]    = compileExpr(args[0]!, cx, st);
    const [right, st2]   = compileExpr(args[1]!, { ...cx, si: cx.si + 1 }, useSlot(st1, cx.si));
    const [notInt, st3]  = ints ? faultLabel(st2, 'RT_FAULT_NOT_INT', name, x.pos) : ['', st2];
    const [combine, st4] = op(st3);
    const isInt = ints ? ['    tst  x0, #1', `    b.ne ${notInt}`] : [];
    return [[
        left, isInt, `    str  x0, ${slot(cx.si)}`,
        right, isInt, `    ldr  x1, ${slot(cx.si)}`,
        combine,
    ], st4];
}

// eq? and ne?. The same word is equal. Otherwise two lists can still be
// equal, which rt_equal works out; but when either side is a literal
// immediate (an integer, a symbol, ()), the words decide.
function compileEquality(x: Pair, name: string, args: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    const negate = name === 'ne?' ? ['    cmp  x0, #RT_TRUE', boolIf('ne')] : [];
    if (args.some(isImmediateLiteral)) {
        return compileBinary(x, name, args, cx, st, (s) => [[compare('eq'), negate], s], false);
    }
    return compileBinary(x, name, args, cx, st, (s) => {
        const [same, s1] = label(s, 'same');
        const [done, s2] = label(s1, 'equal_done');
        return [[
            '    cmp  x1, x0',
            `    b.eq ${same}`,
            '    bl   rt_equal',
            `    b    ${done}`,
            `${same}:`,
            '    mov  x0, #RT_TRUE',
            `${done}:`,
            negate,
        ], s2];
    }, false);
}

function isImmediateLiteral(x: Sexp): boolean {
    if (x.t === 'int' || x.t === 'nil') return true;
    if (x.t === 'sym') return RESERVED_SYMBOLS.includes(x.name);
    return isForm(x, 'quote') && x.t === 'pair' && x.cdr.t === 'pair' && x.cdr.car.t !== 'pair';
}

function checkArity(x: Pair, name: string, args: readonly Sexp[], n: number): void {
    if (args.length !== n) {
        throw new CompileError(`${name} takes ${n} argument${n === 1 ? '' : 's'}, not ${args.length}`, x.pos);
    }
}

// --- lists ------------------------------------------------------------------

// Bump-allocates `bytes` from the process's heap into x2, branching to
// `full` when there isn't room (there's no GC yet: step 9). Clobbers x3,
// x4 and x5.
function alloc(bytes: number, full: string): Code {
    return [
        '    ldr  x2, [x28, #RT_PROC_HEAP_PTR]',
        '    ldr  x3, [x28, #RT_PROC_HEAP_LIMIT]',
        addImm('x4', 'x2', bytes, 'x5'),
        '    cmp  x4, x3',
        `    b.hi ${full}`,
        '    str  x4, [x28, #RT_PROC_HEAP_PTR]',
    ];
}

// dst = src + n, for any n.
function addImm(dst: string, src: string, n: number, scratch: string): Code {
    return n <= 4095 ? `    add  ${dst}, ${src}, #${n}` : [loadWord(scratch, BigInt(n)), `    add  ${dst}, ${src}, ${scratch}`];
}

// (cons x xs): xs must be a list, so every list stays proper.
function compileCons(x: Pair, args: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    checkArity(x, 'cons', args, 2);
    const [head, st1]    = compileExpr(args[0]!, cx, st);
    const [tail, st2]    = compileExpr(args[1]!, { ...cx, si: cx.si + 1 }, useSlot(st1, cx.si));
    const [notList, st3] = faultLabel(st2, 'RT_FAULT_NOT_LIST', 'cons', x.pos);
    const [full, st4]    = faultLabel(st3, 'RT_FAULT_HEAP', 'cons', x.pos);
    return [[
        head, `    str  x0, ${slot(cx.si)}`,
        tail,
        '    and  x1, x0, #RT_TAG_MASK',
        '    cmp  x1, #RT_TAG_LIST',
        `    b.ne ${notList}`,
        alloc(16, full),
        `    ldr  x1, ${slot(cx.si)}`,
        '    stp  x1, x0, [x2]',
        '    orr  x0, x2, #RT_TAG_LIST',
    ], st4];
}

// (list a b ...): the elements wait in slots, then one allocation holds
// all the cells, side by side.
function compileList(x: Pair, args: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    if (args.length === 0) return ['    mov  x0, #RT_NIL', st];
    const [code, st1] = args.reduce<[Code, St]>(([acc, s], arg, i) => {
        const [c, s1] = compileExpr(arg, { ...cx, si: cx.si + i }, s);
        return [[acc, c, `    str  x0, ${slot(cx.si + i)}`], useSlot(s1, cx.si + i)];
    }, [[], st]);
    const [full, st2] = faultLabel(st1, 'RT_FAULT_HEAP', 'list', x.pos);
    const cells = args.map((_, i) => [
        `    ldr  x5, ${slot(cx.si + i)}`,
        `    str  x5, [x2, #${16 * i}]`,
        i + 1 < args.length ? addImm('x6', 'x2', 16 * (i + 1) + RT_TAG_LIST, 'x7') : '    mov  x6, #RT_NIL',
        `    str  x6, [x2, #${16 * i + 8}]`,
    ]);
    return [[code, alloc(16 * args.length, full), cells, '    orr  x0, x2, #RT_TAG_LIST'], st2];
}

// car, cdr, and c[ad]{2,4}r: the letters between c and r, applied right
// to left. Each step needs a cons. Returns null for any other name.
function cxrPath(name: string): readonly string[] | null {
    const middle = name.slice(1, -1);
    const isCxr = name.length >= 3 && name.length <= 6 && name.startsWith('c') && name.endsWith('r')
        && [...middle].every((ch) => ch === 'a' || ch === 'd');
    return isCxr ? [...middle].reverse() : null;
}

function compileCxr(x: Pair, name: string, path: readonly string[], args: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    checkArity(x, name, args, 1);
    const [code, st1]    = compileExpr(args[0]!, cx, st);
    const [notCons, st2] = faultLabel(st1, 'RT_FAULT_NOT_CONS', name, x.pos);
    const steps = path.map((step) => [
        IS_CONS,
        `    b.eq ${notCons}`,
        step === 'a' ? '    ldur x0, [x0, #-1]    // car' : '    ldur x0, [x0, #7]     // cdr',
    ]);
    return [[code, steps], st2];
}

// --- cond -------------------------------------------------------------------

// Each test must be #true or #false; anything else faults, and so does
// running out of clauses. A test that is literally #true needs no check.
// The clause bodies are in tail position if the cond is.
function compileCond(x: Pair, clauses: readonly Sexp[], cx: Cx, st: St): [Code, St] {
    if (clauses.length === 0) throw new CompileError('cond needs at least one clause', x.pos);
    const [end, st1]     = label(st, 'cond_end');
    const [noMatch, st2] = faultLabel(st1, 'RT_FAULT_NO_CLAUSE', 'cond', x.pos);
    const [code, st3]    = clauses.reduce<[Code, St]>(([acc, s], clause) => {
        const [c, s1] = compileClause(x, clause, end, cx, s);
        return [[acc, c], s1];
    }, [[], st2]);
    return [[code, `    b    ${noMatch}`, `${end}:`], st3];
}

function compileClause(x: Pair, clause: Sexp, end: string, cx: Cx, st: St): [Code, St] {
    if (clause.t !== 'pair' || clause.cdr.t !== 'pair') {
        throw new CompileError(`a cond clause is (test body...), not ${show(clause)}`, posOf(clause) ?? x.pos);
    }
    const test = clause.car;
    if (test.t === 'sym' && test.name === '#true') {
        const [body, st1] = compileBody(clause.cdr, cx, st);
        return [[body, `    b    ${end}`], st1];
    }
    const [code, st1]    = compileExpr(test, { ...cx, tail: false }, st);
    const [body, st2]    = compileBody(clause.cdr, cx, st1);
    const [next, st3]    = label(st2, 'cond_next');
    const [notBool, st4] = faultLabel(st3, 'RT_FAULT_NOT_BOOL', 'cond test', posOf(test) ?? clause.pos);
    return [[
        code,
        '    cmp  x0, #RT_FALSE',
        `    b.eq ${next}`,
        '    cmp  x0, #RT_TRUE',
        `    b.ne ${notBool}`,
        body,
        `    b    ${end}`,
        `${next}:`,
    ], st4];
}

// --- helpers ------------------------------------------------------------------

const slot = (si: number): string => `[sp, #${8 * si}]`;

const useSlot = (st: St, si: number): St => (si < st.slots ? st : { ...st, slots: si + 1 });

function lookup(env: Env, name: string): number | null {
    for (; env !== null; env = env.next) if (env.name === name) return env.slot;
    return null;
}

function lookupFn(fns: Fns, name: string): Fn | null {
    for (; fns !== null; fns = fns.next) if (fns.fn.name === name) return fns.fn;
    return null;
}

function label(st: St, hint: string): [string, St] {
    return [`L${hint}_${st.labels}`, { ...st, labels: st.labels + 1 }];
}

type Fault = 'RT_FAULT_NOT_INT' | 'RT_FAULT_OVERFLOW' | 'RT_FAULT_NOT_BOOL' | 'RT_FAULT_NO_CLAUSE' | 'RT_FAULT_STACK'
           | 'RT_FAULT_NOT_CONS' | 'RT_FAULT_NOT_LIST' | 'RT_FAULT_HEAP';

// A label to branch to when `what`, at `pos`, goes wrong: an out-of-line
// call to rt_fault, with the offending value (if any) in x0.
function faultLabel(st: St, fault: Fault, what: string, pos: Pos | null): [string, St] {
    const [name, st1] = label(st, 'fault');
    const site = pos === null ? what : `${what} at ${pos.file}:${pos.line}:${pos.col}`;
    const stub = [
        `${name}:`,
        '    mov  x1, x0',
        `    mov  x0, #${fault}`,
        `    LOADADDR x2, ${name}_site`,
        '    bl   rt_fault',
    ];
    const data = [`${name}_site:`, `    .asciz ${asmString(site)}`];
    return [name, { ...st1, stubs: [st1.stubs, stub], data: [st1.data, data] }];
}

const notYet = (x: Sexp): CompileError => new CompileError(`not supported yet: ${show(x)}`, posOf(x));

// A string as an assembler literal: printable ASCII as is, everything else
// (and " and \) as octal escapes of its UTF-8 bytes.
export function asmString(s: string): string {
    const bytes = [...new TextEncoder().encode(s)];
    const esc   = (b: number): string =>
        b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c ? String.fromCharCode(b) : `\\${b.toString(8).padStart(3, '0')}`;
    return `"${bytes.map(esc).join('')}"`;
}

function flatten(code: Code): string[] {
    const out: string[] = [];
    const todo: Code[] = [code];
    while (todo.length > 0) {
        const c = todo.pop()!;
        if (typeof c === 'string') out.push(c);
        else for (let i = c.length - 1; i >= 0; i--) todo.push(c[i]!);
    }
    return out;
}

// The shortest movz/movn + movk sequence that puts a 64-bit word in reg:
// start from all zeros (movz) or all ones (movn), whichever leaves fewer
// 16-bit chunks to patch with movk.
export function loadWord(reg: string, word: bigint): readonly string[] {
    const w      = BigInt.asUintN(64, word);
    const chunks = [0, 1, 2, 3].map((k) => ({ k, v: Number((w >> BigInt(16 * k)) & 0xffffn) }));
    const ones   = chunks.filter((c) => c.v === 0xffff).length;
    const zeros  = chunks.filter((c) => c.v === 0).length;
    const fill   = ones > zeros ? 0xffff : 0;
    const [first, ...rest] = chunks.filter((c) => c.v !== fill);
    const hex    = (n: number): string => `#0x${n.toString(16)}`;
    const head   = first === undefined
        ? `    ${fill === 0 ? 'movz' : 'movn'} ${reg}, #0`
        : fill === 0
            ? `    movz ${reg}, ${hex(first.v)}, lsl #${16 * first.k}`
            : `    movn ${reg}, ${hex(~first.v & 0xffff)}, lsl #${16 * first.k}`;
    return [head, ...rest.map((c) => `    movk ${reg}, ${hex(c.v)}, lsl #${16 * c.k}`)];
}
